In [30]:
import tensorflow as tf
import numpy as np
import pprint
pp = pprint.PrettyPrinter(indent=4)
sess=tf.InteractiveSession()

# RNN basic

In [ ]:
# cell 생성
hidden_size = 2
cell = tf.contrib.rnn.BasicRNNCell(num_units = hidden_size)
cell = tf.contrib.rnn.BasicLSTMCell(num_units = hidden_size)

cell = tf.keras.layers.SimpleRNNCell(units = hidden_size)

cell = tf.nn.rnn_cell.LSTMCell(num_units=hidden_size, state_is_tuple=True)
cell = tf.nn.rnn_cell.BasicRNNCCell()
cell = tf.nn.rnn_cell.BasicLSTMCell()
cell = tf.nn.rnn_cell.GRUCell(rnn_size)


# 실행
outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)

# _states = > 중간의 그것 

In [ ]:
sess=tf.Session()

hidden_size = 2 # 결과 size가 2
cell = tf.contrib.rnn.BasicLSTMCell(num_units = hidden_size)

x_data = np.array([[[1,0,0,0]]], dtype = np.float32)
outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)

sess.run(tf.global_variables_initializer())
pp.pprint(outputs.eval(session=sess))

In [24]:
print(l)

[0. 0. 1. 0.]


In [19]:
sess=tf.Session()
with tf.variable_scope("cell_1") : 
    # One cell RNN input_dim(4) -> output_dim(2), sequence : 5 <- x_data원소개수=5
    hidden_size = 2
    cell = tf.contrib.rnn.BasicLSTMCell(num_units = hidden_size)
    x_data=np.arange(4, dtype=np.int32)
    x_data=tf.one_hot(x_data, 4)
    x_data=tf.reshape(x_data, [4,4])
    h,e,l,o = x_data.eval(session=sess)
    x_data = np.array([[h,e,l,l,o]], dtype=np.float32)
    outputs, states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval(session=sess))
    print(outputs.shape)#output의 shape는 (input 문자열 개수,sequence,hidden_layer)
    
# h = [1,0,0,0]; e=[0,1,0,0]; l=[0,0,1,0]; o=[0,0,0,1]
# x_data = np.array([[h,e,l,o]])

array([[[ 0.09565353,  0.04719898],
        [ 0.12111682,  0.17112955],
        [ 0.03183326,  0.21401575],
        [-0.05653878,  0.25052023],
        [ 0.04456245,  0.17628841]]], dtype=float32)


## Batching input

In [31]:
with tf.variable_scope("batch_3"):
    # One cell RNN input_dim(4) -> output_dim(2), sequence = 5, batch = 3
    # 3 batches "hello", "eolll", "lleel"
    hidden_batch = 2
    x_data = np.array([[h,e,l,l,o],
                      [e,o,l,l,l],
                      [l,l,e,e,l]], dtype=np.float32)
    pp.pprint(x_data)
    
    cell = tf.nn.rnn_cell.LSTMCell(num_units=2, state_is_tuple=True)
    outputs, states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval(session=sess))

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]],

       [[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.]],

       [[0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]], dtype=float32)
array([[[ 0.08781026, -0.14008562],
        [ 0.10244749, -0.18780306],
        [ 0.10326943, -0.06102803],
        [ 0.13322932,  0.02323322],
        [ 0.22909525, -0.01672404]],

       [[-0.00094913, -0.11873899],
        [ 0.05858904, -0.08596512],
        [ 0.08082239, -0.01478801],
        [ 0.1173007 ,  0.04541206],
        [ 0.14715661,  0.07848615]],

       [[ 0.05084566,  0.04822775],
        [ 0.09425249,  0.07605527],
        [ 0.13481486, -0.06377019],
        [ 0.10928101, -0.1583339 ],
        [ 0.10811098, -0.04322229]]], dtype=float32)


In [22]:
print("r")

r


In [33]:
outputs.eval()[1,1,]

array([[[ 0.08781026, -0.14008562],
        [ 0.10244749, -0.18780306],
        [ 0.10326943, -0.06102803],
        [ 0.13322932,  0.02323322],
        [ 0.22909525, -0.01672404]],

       [[-0.00094913, -0.11873899],
        [ 0.05858904, -0.08596512],
        [ 0.08082239, -0.01478801],
        [ 0.1173007 ,  0.04541206],
        [ 0.14715661,  0.07848615]],

       [[ 0.05084566,  0.04822775],
        [ 0.09425249,  0.07605527],
        [ 0.13481486, -0.06377019],
        [ 0.10928101, -0.1583339 ],
        [ 0.10811098, -0.04322229]]], dtype=float32)