- text : "hihello" => "o" 다음 문자가 없기 때문에 hihell 까지만 input
- unique chars(vocabulary, voc): h, i, e, l, o
- voc index= h:0, i:1, e:2, 1:3, o:4

- sequence : 6
- hidden_layer : 5
- batch : 1
- input_dimension : 5

In [9]:
import tensorflow as tf
import numpy as np
import pprint
sess=tf.InteractiveSession()

## Data creation

In [36]:
dic_char = {}
for idx, i in enumerate(list("hielo")):
    dic_char[i]=idx
x_data = list("hihell")
x_data = [dic_char[i] for i in x_data]
x_data = tf.reshape(tf.one_hot(x_data, len(dic_char)), [1,-1,5])
y_data = np.array([[dic_char[i] for i in list("ihello")]])
print(y_data)
print(x_data.eval())


[[1 0 2 3 3 4]]
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0.]]]


In [43]:
x_data=np.array(x_data.eval())

In [45]:
print(dic_char)

{'h': 0, 'i': 1, 'e': 2, 'l': 3, 'o': 4}


In [47]:
dic_char_num = {0:"h",1:"i",2:"e",3:"l",4:"o"}

## Feed to RNN

In [48]:
#parameters
with tf.variable_scope("hife13ee33"):
    sequence_length = 6
    hidden_size = 5
    input_dim = 5
    batch_size=1

    x = tf.placeholder(tf.float32, [None, sequence_length, input_dim])
    y = tf.placeholder(tf.int32, [None, sequence_length])

    cell = tf.contrib.rnn.BasicLSTMCell(hidden_size, state_is_tuple=True)
    #  초기 output의 state를 정함
    initial_state = cell.zero_state(batch_size, tf.float32)
    # initial_state의 shape는 [batch_size, hidden_layer]
    outputs, states = tf.nn.dynamic_rnn(cell, x, initial_state=initial_state,
                                       dtype=tf.float32)
    weights = tf.ones([batch_size, sequence_length])
    
    sequence_loss = tf.contrib.seq2seq.sequence_loss(
                logits=outputs, targets=y, weights=weights) #각 batch 의 loss
    loss = tf.reduce_mean(sequence_loss) # 모든 batch의 loss
    train = tf.train.AdamOptimizer(learning_rate=0.1).minimize(loss)
    
    prediction = tf.argmax(outputs, axis=2)
    
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        for i in range(2000):
            l, _ = sess.run([loss,train], feed_dict={x:x_data,
                                                    y:y_data})
            result = sess.run(prediction, feed_dict={x:x_data})
            print(i, "loss", l, "prediction", result, "true", y_data)
            result_str = [dic_char_num[c] for c in np.squeeze(result)] # 각숫자해당문자열
            print("prediction", "".join(result_str)) #문자열 합침
    

0 loss 1.622358 prediction [[1 3 2 2 4 4]] true [[1 0 2 3 3 4]]
prediction ileeoo
1 loss 1.5568142 prediction [[2 2 2 2 4 4]] true [[1 0 2 3 3 4]]
prediction eeeeoo
2 loss 1.4967636 prediction [[2 2 2 4 4 4]] true [[1 0 2 3 3 4]]
prediction eeeooo
3 loss 1.4313016 prediction [[2 3 2 3 4 4]] true [[1 0 2 3 3 4]]
prediction eleloo
4 loss 1.3611711 prediction [[2 3 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction elello
5 loss 1.2905995 prediction [[2 3 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction elelll
6 loss 1.2248923 prediction [[2 3 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction elelll
7 loss 1.1657149 prediction [[2 3 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction elelll
8 loss 1.1144158 prediction [[2 3 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction elelll
9 loss 1.0715754 prediction [[2 2 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction eeelll
10 loss 1.0370574 prediction [[1 2 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction ieelll
11 loss 1.0085233 prediction [[1 2 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction ieelll
12 

99 loss 0.7182352 prediction [[1 0 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction ihelll
100 loss 0.71820074 prediction [[1 0 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction ihelll
101 loss 0.7181699 prediction [[1 0 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction ihelll
102 loss 0.71814066 prediction [[1 0 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction ihelll
103 loss 0.7181111 prediction [[1 0 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction ihelll
104 loss 0.71808094 prediction [[1 0 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction ihelll
105 loss 0.7180509 prediction [[1 0 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction ihelll
106 loss 0.71802217 prediction [[1 0 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction ihelll
107 loss 0.71799546 prediction [[1 0 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction ihelll
108 loss 0.7179699 prediction [[1 0 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction ihelll
109 loss 0.7179449 prediction [[1 0 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction ihelll
110 loss 0.7179201 prediction [[1 0 2 3 3 3]] true [[1 0 2 3 

202 loss 0.6994348 prediction [[1 0 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction ihelll
203 loss 0.6995477 prediction [[1 0 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction ihelll
204 loss 0.69954616 prediction [[1 0 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction ihelll
205 loss 0.6994591 prediction [[1 0 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction ihelll
206 loss 0.698924 prediction [[1 0 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction ihelll
207 loss 0.6991115 prediction [[1 0 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction ihelll
208 loss 0.69936055 prediction [[1 0 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction ihelll
209 loss 0.69854516 prediction [[1 0 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction ihelll
210 loss 0.6992225 prediction [[1 0 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction ihelll
211 loss 0.699434 prediction [[1 0 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction ihelll
212 loss 0.69849235 prediction [[1 0 2 3 3 3]] true [[1 0 2 3 3 4]]
prediction ihelll
213 loss 0.6997459 prediction [[1 0 2 3 3 3]] true [[1 0 2 3 3 

309 loss 0.6475425 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
310 loss 0.6474781 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
311 loss 0.64741457 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
312 loss 0.64735216 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
313 loss 0.64729065 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
314 loss 0.64723 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
315 loss 0.64717025 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
316 loss 0.64711136 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
317 loss 0.6470533 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
318 loss 0.6469962 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
319 loss 0.6469397 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
320 loss 0.64688396 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 

418 loss 0.6434483 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
419 loss 0.64342487 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
420 loss 0.6434016 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
421 loss 0.6433786 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
422 loss 0.6433556 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
423 loss 0.6433329 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
424 loss 0.6433101 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
425 loss 0.64328766 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
426 loss 0.6432653 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
427 loss 0.643243 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
428 loss 0.64322084 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
429 loss 0.6431988 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 

531 loss 0.64143986 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
532 loss 0.6414261 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
533 loss 0.6414124 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
534 loss 0.6413989 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
535 loss 0.6413853 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
536 loss 0.64137185 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
537 loss 0.6413583 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
538 loss 0.64134496 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
539 loss 0.6413316 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
540 loss 0.6413184 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
541 loss 0.6413051 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
542 loss 0.64129186 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 

638 loss 0.6402119 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
639 loss 0.6402022 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
640 loss 0.6401927 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
641 loss 0.64018303 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
642 loss 0.64017355 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
643 loss 0.640164 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
644 loss 0.64015454 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
645 loss 0.640145 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
646 loss 0.6401356 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
647 loss 0.64012617 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
648 loss 0.64011675 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
649 loss 0.6401074 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3

prediction ihello
764 loss 0.63917917 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
765 loss 0.63917226 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
766 loss 0.6391653 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
767 loss 0.6391583 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
768 loss 0.6391514 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
769 loss 0.6391445 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
770 loss 0.63913757 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
771 loss 0.6391307 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
772 loss 0.63912386 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
773 loss 0.639117 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
774 loss 0.63911015 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
775 loss 0.63910335 prediction [[1 0 2 3 3 

prediction ihello
881 loss 0.63845605 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
882 loss 0.6384506 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
883 loss 0.63844514 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
884 loss 0.6384397 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
885 loss 0.6384343 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
886 loss 0.6384288 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
887 loss 0.6384234 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
888 loss 0.63841796 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
889 loss 0.63841254 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
890 loss 0.6384071 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
891 loss 0.6384018 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
892 loss 0.63839644 prediction [[1 0 2 3 3 

1003 loss 0.637856 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1004 loss 0.6378515 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1005 loss 0.6378472 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1006 loss 0.6378427 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1007 loss 0.6378383 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1008 loss 0.6378339 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1009 loss 0.63782954 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1010 loss 0.63782513 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1011 loss 0.6378208 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1012 loss 0.63781637 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1013 loss 0.63781196 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1014 loss 0.63780767 prediction [[1 0 2 3 3 4]] tru

1101 loss 0.6374532 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1102 loss 0.6374493 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1103 loss 0.63744557 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1104 loss 0.6374417 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1105 loss 0.6374379 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1106 loss 0.6374341 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1107 loss 0.63743037 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1108 loss 0.63742656 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1109 loss 0.63742274 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1110 loss 0.63741904 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1111 loss 0.6374152 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1112 loss 0.6374114 prediction [[1 0 2 3 3 4]] tr

1200 loss 0.63709885 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1201 loss 0.6370955 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1202 loss 0.6370922 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1203 loss 0.63708884 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1204 loss 0.63708544 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1205 loss 0.63708216 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1206 loss 0.63707876 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1207 loss 0.63707536 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1208 loss 0.63707215 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1209 loss 0.6370688 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1210 loss 0.6370655 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1211 loss 0.63706213 prediction [[1 0 2 3 3 4]]

1309 loss 0.6367553 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1310 loss 0.6367523 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1311 loss 0.6367493 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1312 loss 0.6367464 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1313 loss 0.63674337 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1314 loss 0.6367405 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1315 loss 0.6367375 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1316 loss 0.63673455 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1317 loss 0.6367317 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1318 loss 0.6367287 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1319 loss 0.6367258 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1320 loss 0.6367228 prediction [[1 0 2 3 3 4]] true 

1427 loss 0.63642526 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1428 loss 0.6364226 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1429 loss 0.63641995 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1430 loss 0.6364173 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1431 loss 0.6364147 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1432 loss 0.63641196 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1433 loss 0.63640934 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1434 loss 0.6364068 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1435 loss 0.63640416 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1436 loss 0.63640153 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1437 loss 0.63639885 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1438 loss 0.63639635 prediction [[1 0 2 3 3 4]]

1543 loss 0.6361333 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1544 loss 0.6361309 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1545 loss 0.6361285 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1546 loss 0.63612616 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1547 loss 0.6361238 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1548 loss 0.6361214 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1549 loss 0.63611895 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1550 loss 0.63611656 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1551 loss 0.63611424 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1552 loss 0.63611186 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1553 loss 0.6361094 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1554 loss 0.636107 prediction [[1 0 2 3 3 4]] tru

1660 loss 0.63586444 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1661 loss 0.6358623 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1662 loss 0.6358601 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1663 loss 0.63585794 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1664 loss 0.6358557 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1665 loss 0.6358535 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1666 loss 0.6358514 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1667 loss 0.63584906 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1668 loss 0.6358469 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1669 loss 0.6358447 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1670 loss 0.6358425 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1671 loss 0.63584036 prediction [[1 0 2 3 3 4]] tru

1768 loss 0.6356347 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1769 loss 0.6356326 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1770 loss 0.63563055 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1771 loss 0.6356284 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1772 loss 0.6356265 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1773 loss 0.63562447 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1774 loss 0.6356224 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1775 loss 0.63562036 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1776 loss 0.63561827 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1777 loss 0.63561624 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1778 loss 0.63561416 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1779 loss 0.63561213 prediction [[1 0 2 3 3 4]] 

1866 loss 0.63543886 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1867 loss 0.6354369 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1868 loss 0.6354349 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1869 loss 0.635433 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1870 loss 0.63543105 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1871 loss 0.63542914 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1872 loss 0.6354272 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1873 loss 0.63542527 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1874 loss 0.6354233 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1875 loss 0.63542145 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1876 loss 0.63541955 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1877 loss 0.6354175 prediction [[1 0 2 3 3 4]] tr

1964 loss 0.63525337 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1965 loss 0.6352515 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1966 loss 0.6352496 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1967 loss 0.63524777 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1968 loss 0.6352459 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1969 loss 0.63524413 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1970 loss 0.6352423 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1971 loss 0.6352405 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1972 loss 0.6352386 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1973 loss 0.6352368 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1974 loss 0.6352349 prediction [[1 0 2 3 3 4]] true [[1 0 2 3 3 4]]
prediction ihello
1975 loss 0.63523304 prediction [[1 0 2 3 3 4]] tru

In [20]:
cell.zero_state(5, tf.float32)

LSTMStateTuple(c=<tf.Tensor 'BasicLSTMCellZeroState_2/zeros:0' shape=(5, 6) dtype=float32>, h=<tf.Tensor 'BasicLSTMCellZeroState_2/zeros_1:0' shape=(5, 6) dtype=float32>)

## Cost : sequence_loss

In [24]:
# [batch_size, sequence_length]
y_data = tf.constant([[1,1,1]])
# [batch_size, sequece_length, hidden_size]
prediction1 = tf.constant([[[0.2,0.8],[0.2,0.8],[0.2,0.8]]])
prediction2 = tf.constant([[[0.1,0.9],[0.1,0.9],[0.1,0.9]]])
# [batch_size, sequence_length]
weights = tf.constant([[1,1,1]], dtype=tf.float32)
weights = tf.ones([batch_size, sequence_length])

sequence_loss1 = tf.contrib.seq2seq.sequence_loss(logits=prediction1,
                        targets = y_data, weights = weights)
sequence_loss2 = tf.contrib.seq2seq.sequence_loss(logits=prediction2,
                        targets = y_data, weights = weights)
# 형태가 같지 않아도 알아서 계산해줌!

sess.run(tf.global_variables_initializer())
print(sequence_loss1.eval())
print(sequence_loss2.eval())

0.437488
0.3711007


# Training

In [ ]:
with tf.Session() as sess:
        sess.run(tf.global_variabels_initializer())
        for i in range(2000):
            l, _ = sess.run([loss,train], feed_didt={x:x_one_hot,
                                                    y:y_data})
            result = sess.run(prediction, feed_dict={x:x_one_hot})
            print(i, "loss", l, "prediction", result, "true", y_data)
            result_str = [idx2char[c] for c in np.squeeze(result)] # 각숫자해당문자열
            print("prediction", "".join(result_str)) #문자열 합침