## Hypothesis not using matrix 

### *H(x1,x2,x3) = x1w1+ x2w2 + x3w3 *

In [11]:
import tensorflow as tf

x1_data=[73,93,89,86,73]
x2_data=[80,88,91,98,66]
x3_data=[75,93,90,100,70]
y_data=[152,185,180,196,142]

# placeholders for a tensor that will be always fed
x1=tf.placeholder(tf.float32,shape=[None]) #1차원이고 원소 개수는 명시하지 않아주었음
x2=tf.placeholder(tf.float32)
x3=tf.placeholder(tf.float32)
# placeholder 는 반드시 dtype 을 명시해주어야 함!

y=tf.placeholder(tf.float32, shape=[None])

w1=tf.Variable(tf.random_normal([1]),name="weight1")
w2=tf.Variable(tf.random_normal([1]),name="weight2")
w3=tf.Variable(tf.random_normal([1]),name="weight3")

b=tf.Variable(tf.random_normal([1]),name="bias")

hypothesis=x1*w1+x2*w2+x3*w3+b

# cost/Loss function
cost=tf.reduce_mean(tf.square(hypothesis-y))

#Minimize Need a very small learning rate for this data set
optimizer=tf.train.GradientDescentOptimizer(learning_rate=1e-5) # e는 1/10..?
train=optimizer.minimize(cost)

# Launch the graph in a session
sess=tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val,_ = sess.run([cost,hypothesis,train],
                                  feed_dict={x1:x1_data,x2:x2_data,x3:x3_data,y:y_data})
    if step%10==0:
        print(cost_val,hy_val)

81360.85 [-103.32902  -117.69936  -119.384285 -132.0654    -87.62276 ]
28.529638 [151.12433 187.94537 181.86761 185.14075 145.43436]
27.30167 [152.0159  188.98094 182.90617 186.27997 146.21133]
27.051754 [152.02924 188.96164 182.90497 186.32431 146.18396]
26.804455 [152.03946 188.93884 182.90022 186.36469 146.15399]
26.559711 [152.04962 188.91618 182.89548 186.40485 146.12418]
26.317387 [152.05971 188.89362 182.89075 186.44481 146.09451]
26.077572 [152.0697  188.87117 182.886   186.48454 146.06499]
25.840244 [152.07967 188.84888 182.88133 186.52411 146.03564]
25.605343 [152.08954 188.82668 182.87663 186.56345 146.00645]
25.372763 [152.09938 188.80461 182.872   186.60263 145.97743]
25.142645 [152.10912 188.78267 182.86734 186.64157 145.94853]
24.914873 [152.1188  188.76083 182.86272 186.68033 145.91982]
24.689356 [152.12842 188.73914 182.85811 186.7189  145.89122]
24.466072 [152.138   188.71754 182.85352 186.75731 145.86281]
24.245253 [152.14749 188.69608 182.84895 186.79547 145.83453]


8.669727 [152.93436 186.769   182.39296 190.34177 143.26665]
8.607355 [152.93813 186.7584  182.39006 190.36226 143.25227]
8.5456295 [152.94183 186.74788 182.38716 190.38263 143.23799]
8.484488 [152.94556 186.73743 182.38431 190.40294 143.2238 ]
8.423931 [152.94922 186.72702 182.38144 190.42313 143.20966]
8.363982 [152.95285 186.71667 182.37857 190.4432  143.1956 ]
8.304615 [152.95645 186.70639 182.37572 190.4632  143.18164]
8.2457905 [152.96    186.69617 182.37288 190.4831  143.16771]
8.18756 [152.96358 186.686   182.37007 190.50291 143.15392]
8.129839 [152.96709 186.67589 182.36723 190.52263 143.14015]
8.072754 [152.97057 186.66585 182.36444 190.54224 143.12648]
8.016146 [152.97401 186.65584 182.36162 190.56175 143.11285]
7.9601583 [152.97745 186.6459  182.35886 190.58118 143.09933]
7.904695 [152.98085 186.63602 182.35606 190.6005  143.08589]
7.8497543 [152.9842  186.62619 182.35329 190.61972 143.0725 ]
7.7952895 [152.98755 186.61642 182.35052 190.63889 143.05917]
7.7413917 [152.99086

## Hypothesis using matrix

In [15]:
x_data=[[73.,80.,75.],[93.,88.,93.],[89.,91.,90.],[86.,98.,100.],[73.,66.,70.]]
y_data=[[152.],[185.],[180.],[196.],[142.]]

# placeholders for a tensor that wiil be always fed.
x = tf.placeholder(tf.float32, shape=[None,3]) # 데이터의 개수는 정하지 않고 feature 은 3개
# 행은 정하지 않고 열 개수만 고정 # 3열만 고정
y = tf.placeholder(tf.float32, shape=[None,1])

w = tf.Variable(tf.random_normal([3,1]), name="weight")
b = tf.Variable(tf.random_normal([1]), name="bias")

# Hypothesis
hypothesis = tf.matmul(x,w) + b # x와 w를 일반 곱이 아닌 행렬곱을 해주어야 함!!!

# Simplified cost/Loss function
cost=tf.reduce_mean(tf.square(hypothesis-y))
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train=optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val,_ = sess.run([cost,hypothesis,train], feed_dict={x:x_data,y:y_data})
    if step%500==0:
        print(step,"cost:",cost_val,"prediction",hy_val)
    # hypothesis 또한 노드에 얽혀있는 연산이기 때문에 반드시 run 을 해준 뒤 값을 반환해야 함!

0 cost: 82.07899 prediction [[147.8952 ]
 [182.2074 ]
 [177.30785]
 [176.54759]
 [141.67896]]
500 cost: 28.33873 prediction [[153.97836]
 [187.83444]
 [183.6958 ]
 [185.7441 ]
 [145.30199]]
1000 cost: 19.74232 prediction [[154.2721 ]
 [186.97012]
 [183.45026]
 [187.44102]
 [144.12308]]
1500 cost: 14.391077 prediction [[154.45416]
 [186.32413]
 [183.24072]
 [188.77666]
 [143.22482]]
2000 cost: 10.983575 prediction [[154.55264]
 [185.84505]
 [183.05995]
 [189.83308]
 [142.54187]]


## Loading data from file


In [35]:
import numpy as np
import tensorflow as tf
tf.set_random_seed(777) #for reproducibility  #random number에서의 대표성을 위해 seed 를 설정

#데이터 읽어오기
xy=np.loadtxt("./data-01-test-score.csv", delimiter=",",dtype=np.float32) # numpy 는 같은 형식의 데이터만 저장가능
x_data=xy[:,0:-1] # 한칸씩 오른쪽으로 간다고 생각하면 됨!
y_data=xy[:,[-1]] # y_data=xy[:,-1] 로 하게 되면 [a,b,c,d,e] 같은 형식으로 변해버리게 되기 때문에
#반드시 [-1]를 해주어야 함!

# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data)) # len 은 몇 행인지를 반환해줌
print(y_data.shape, y_data, len(y_data))

# placeholders for a tensor that will be always fed.
x = tf.placeholder(tf.float32, shape=[None,3])
y = tf.placeholder(tf.float32, shape=[None,1]) # 몇행 몇열로 봐도 무방

w = tf.Variable(tf.random_normal([3,1]), name="weight")
b= tf. Variable(tf.random_normal([1]), name="bias")

# Hypotehsis
hypothesis = tf.matmul(x,w) + b

# Simplified cost/Loss function
cost= tf.reduce_mean(tf.square(hypothesis-y))

# MInimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train=optimizer.minimize(cost)

# Launch the graph in a session.
sess=tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
# Set up feed_dict variables inside the loop
for step in range(2001):
    cost_val, hy_val,_ = sess.run([cost,hypothesis,train],
                                 feed_dict={x:x_data,y:y_data})
    if step%100 ==0:
        print(step,"cost",cost_val,"hypothesis",hy_val)
    
# Ask my score
print("Your score will be", sess.run(hypothesis, feed_dict={x:[[100,70,101]]}))
# 1개의 데이터라도 x 데이터의 형식이 [None, 3] 이기 때문에 [[]] 형식으로 집어넣어줘야 함
print("Others scores wiil be", sess.run(hypothesis, feed_dict={x:[[60,70,100],[90,100,80]]}))
    

(7, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 69.  91.  90.]
 [ 96.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  88.  70.]
 [ 53.  46.  55.]] 7
(7, 1) [[152.]
 [185.]
 [180.]
 [180.]
 [196.]
 [142.]
 [101.]] 7
0 cost 163887.42 hypothesis [[-219.53613]
 [-271.0702 ]
 [-223.74281]
 [-277.69568]
 [-285.632  ]
 [-222.35889]
 [-151.8882 ]]
100 cost 39.692097 hypothesis [[152.80746]
 [176.69633]
 [184.65823]
 [174.80287]
 [194.72491]
 [154.52274]
 [ 99.95703]]
200 cost 34.194416 hypothesis [[152.6132 ]
 [177.21178]
 [183.94238]
 [175.2111 ]
 [194.91585]
 [153.76677]
 [100.53062]]
300 cost 29.689404 hypothesis [[152.43631]
 [177.67752]
 [183.30676]
 [175.57458]
 [195.08984]
 [153.0755 ]
 [101.05186]]
400 cost 25.993654 hypothesis [[152.2751 ]
 [178.09846]
 [182.74292]
 [175.89801]
 [195.24854]
 [152.44307]
 [101.52573]]
500 cost 22.957897 hypothesis [[152.12814]
 [178.47897]
 [182.24329]
 [176.18556]
 [195.39331]
 [151.86404]
 [101.95674]]
600 cost 20.460827 hypothesis [[151.99405]
 [178.823  ]
 [181

numpy 로 데이터를 한번에 저장해서 훈련을 시키려고 하면 데이터 용량이 많을 때 오류가 발생할 수 있음  
따라서 quene 로 쌓고 조금씩 빨아들이는 방법을 사용

## Quene Runners

In [ ]:
filename_queue=tf.train.strin_input_producer(["a","b","c"], shuffle=False, name="filename_queue")
# a가 제일 위에, 그 다음에 b, 그다음에 c 순으로 쌓이게 됨

reader=tf.TextLineReader()
key,value=reader.read(filename_queue) # queue 에 쌓았기 때문에 맨 위에 head 같은게 존재할 수도 있음
#그걸 빼고 파일이름만을 읽어오겠다는 뜻

record_defaults = [[0.],[0.],[0.],[0.],[0.]] #각 열의 데이터 타입은 float 이고 null 값을 0으로 채우겠다
# 만약 다 같으면
record_defaults = [[0.] for row in range(10000)]
xy = tf.decode_csv(value, record_defaults=record_defaults)

## tf.train.batch

In [ ]:
# batch 는 이제 몇개 데이터를 분할해서 불러올 수 있게 하는 역할을 함!
# 물을 빨아들이는 펌프같은 역할

# collect batches of csv in
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1],xy[-1:]], batch_size=10)
# 행은 배치 사이즈로 정해지기 때문에 꺼내오기 때문에 열만 지정해주면 됨.
# 10행씩 꺼내옴
# 하나하나의 행을 꺼내서 쌓음.
# xy[-1] 만 하면 원소만 꺼내서 쌓는 것, xy[-1:] 하면 이에 해당하는 리스트를 리스트 안에 쌓는 것.
... 모델 정의

sess=tf.Session()

# Start populating the filename queue
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    
coord.request.stop()
coord.join(threads)





In [1]:
import tensorflow as tf
filename_queue = tf.train.string_input_producer(["./data-01-test-score.csv"], shuffle=False, name="filename_queue")

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decorded result.
record_defaults = [[0.] for i in range(4)] # 열들의 형식을 정함
xy = tf.decode_csv(value, record_defaults=record_defaults) # 해당 파일이름들의 파일 내용을 csv 로 불러옴

# collect batches of csv in
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1],xy[-1:]], batch_size=2) # xy[-1] 하게 되면 또 마음대로 하나로바꿔줌
# xy[-1:] 해줘야지 원래 형식 그대로 가져옴 
# batch 에서의 열 슬라이싱은 [-1] 이런 식으로 안에 integer 가 들어오거나 0:3 3: 형식의 슬라이싱만 가능
# xy[[-1]] 불가능
    
# placeholders for a tensor that will be always fed
x = tf.placeholder(tf.float32, shape=[None,3])
y = tf.placeholder(tf.float32, shape=[None,1])

w= tf.Variable(tf.random_normal([3,1]),name="weight")
b= tf.Variable(tf.random_normal([1]), name="bias")

# Hypothesis
hypothesis = tf.matmul(x,w) + b

# Simplified cost/Loss Function
cost = tf.reduce_mean(tf.square(hypothesis-y))

# MInimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train=optimizer.minimize(cost)

#Launch the graph in a session
sess=tf.Session()
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)
# 큐를 해당 모델에 실행시킴

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])  # 배치를 실행시킴
    cost_val, hy_val,_ = sess.run([cost,hypothesis, train], feed_dict={x:x_batch, y:y_batch})
    # 조금씩 뽑아온 데이터로 해당 모델을 실행하면서 모델을 업데이트 시킴
    if step%200==0:
        print(step, cost_val, hy_val)
        print(x_batch, y_batch)
        
coord.request_stop()
coord.join(threads)

# queue 를 멈춤



Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLineDataset`.
Instructions for updating:
Queue-base

In [3]:
import tensorflow as tf
filename_queue = tf.train.string_input_producer(["./data-01-test-score.csv","./data-02-test-score.csv"], shuffle=False, name="filename_queue")

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decorded result.
record_defaults = [[0.] for i in range(4)] # 열들의 형식을 정함
xy = tf.decode_csv(value, record_defaults=record_defaults) # 해당 파일이름들의 파일 내용을 csv 로 불러옴

# collect batches of csv in
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1],xy[-1:]], batch_size=2) # xy[-1] 하게 되면 또 마음대로 하나로바꿔줌
# xy[-1:] 해줘야지 원래 형식 그대로 가져옴 
# batch 에서의 열 슬라이싱은 [-1] 이런 식으로 안에 integer 가 들어오거나 0:3 3: 형식의 슬라이싱만 가능
# xy[[-1]] 불가능
    
# placeholders for a tensor that will be always fed
x = tf.placeholder(tf.float32, shape=[None,3])
y = tf.placeholder(tf.float32, shape=[None,1])

w= tf.Variable(tf.random_normal([3,1]),name="weight")
b= tf.Variable(tf.random_normal([1]), name="bias")

# Hypothesis
hypothesis = tf.matmul(x,w) + b

# Simplified cost/Loss Function
cost = tf.reduce_mean(tf.square(hypothesis-y))

# MInimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train=optimizer.minimize(cost)

#Launch the graph in a session
sess=tf.Session()
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)
# 큐를 포함한 모델을 만든 뒤에
# 큐를 해당 모델에 실행시킴

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])  # 배치를 실행시킴
    cost_val, hy_val,_ = sess.run([cost,hypothesis, train], feed_dict={x:x_batch, y:y_batch})
    print(x_batch, y_batch)
    # 조금씩 뽑아온 데이터로 해당 모델을 실행하면서 모델을 업데이트 시킴
    if step%200==0:
        print(step, cost_val, hy_val)
        
        
coord.request_stop()
coord.join(threads)

# queue 를 멈춤



[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
0 80799.19 [[ -93.33046]
 [-133.45149]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  2.  3.]] [[101.]
 [152.]]
[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  2.  3.]] [[101.]
 [152.]]
[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  2.  3.]] [[101.]
 [152.]]
[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]]

[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  2.  3.]] [[101.]
 [152.]]
[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  2.  3.]] [[101.]
 [152.]]
[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
200 28937.982 [[ 9.572486]
 [15.375737]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  2.  3.]] [[101.]
 [152.]]
[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]

[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  2.  3.]] [[101.]
 [152.]]
[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  2.  3.]] [[101.]
 [152.]]
[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
400 125.50913 [[194.81114]
 [174.37431]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  2.  3.]] [[101.]
 [152.]]
[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]

[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  2.  3.]] [[101.]
 [152.]]
[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  2.  3.]] [[101.]
 [152.]]
[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  

[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  2.  3.]] [[101.]
 [152.]]
[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  2.  3.]] [[101.]
 [152.]]
[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  2.  3.]] [[101.]
 [152.]]
[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 8

[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  2.  3.]] [[101.]
 [152.]]
[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  2.  3.]] [[101.]
 [152.]]
[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
1000 143.79839 [[158.93474]
 [100.09922]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.

[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  2.  3.]] [[101.]
 [152.]]
1200 10741.65 [[97.91904 ]
 [ 5.460551]]
[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  2.  3.]] [[101.]
 [152.]]
[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]

 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  2.  3.]] [[101.]
 [152.]]
[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  2.  3.]] [[101.]
 [152.]]
[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  2.  3.]] [[101.]
 [152.]]
[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.

[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  2.  3.]] [[101.]
 [152.]]
[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  2.  3.]] [[101.]
 [152.]]
[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  

[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  2.  3.]] [[101.]
 [152.]]
[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  2.  3.]] [[101.]
 [152.]]
[[4. 5. 6.]
 [7. 8. 9.]] [[185.]
 [180.]]
[[ 96.  91.  90.]
 [ 96.  98. 100.]] [[180.]
 [196.]]
[[73. 88. 70.]
 [53. 46. 55.]] [[142.]
 [101.]]
[[73. 80. 75.]
 [93. 88. 93.]] [[152.]
 [185.]]
[[69. 91. 90.]
 [96. 91. 90.]] [[180.]
 [180.]]
[[ 96.  98. 100.]
 [ 73.  88.  70.]] [[196.]
 [142.]]
[[53. 46. 55.]
 [ 1.  

## shuffle_batch

In [57]:
#dequeue는 더 큰 버퍼에서 무작위로 샘플링 할 버퍼가 얼마나 큰지를 정의합니다. 
#더 나은 셔플 링이지만 더 느린 시작 및 더 많은 메모리 사용을 의미합니다. 
#용량은 dequeue보다 커야하고 더 큰 양은 프리 페치 최대 값을 결정합니다.


min_after_dequeue= 10000 # 큐에 있는 요소의 최소수, 높을수록 무작위로 배치
capacity = min_after_dequeue + 3 * batch_size  # 한 번에 대기열에 몇개의 요소를 저장할 수 있는지, 최댓값

example_batch, label_batch = tf.train.shuffle_batch([example, label], batch_size=batch_size, capacity=capacity,
                                                   min_after_dequeue=min_after_dequeue)
# tf.train.batch() 대신 사용 가능

[[1], [1], [1]]
