# multinational classification

In [28]:
import tensorflow as tf

## softmax function

In [ ]:
hypothesis = tf.nn.softmax(tf.matmul(x,w)+b)

# tf.matmul(x,w)+b 로 나온 score 을 softmax fuction 을 통해 probability 로 바꿈!
# 하나의 instance 로 나온 확률들의 합은 1

cost = tf.reduce_mean(-tf.reduce_sum(y*tf.log(hypothesis), axis=1)) # 가로로 더한 값. = 하나의 instance 에 대한 cost 이기 때문
                      # axis=1 을 붙여주지 않으면 전체 합이 나옴
                      
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

In [67]:
x_data = [[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

x = tf.placeholder("float",[None, 4])
y = tf.placeholder("float",[None, 3])
# tf.float32 대신 "float" 도 가능
nb_classes = 3

w = tf.Variable(tf.random_normal([4,nb_classes]), name="weight")
b = tf.Variable(tf.random_normal([1]),name = "bias")

# tf.nn.softmax computes softmax activations
# sotfmax = exp(Logits)/reduce_sum(exp(Logits),dim)
hypothesis = tf.nn.softmax(tf.matmul(x,w)+b)

#Cross entropy cost/Loss
cost = tf.reduce_mean(-tf.reduce_sum(y*tf.log(hypothesis), axis=1))
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

#Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for i in range(2001):
        sess.run(train, feed_dict = {x:x_data, y:y_data})
        
        if i%500==0:
            print(i, sess.run(cost, feed_dict = {x:x_data,y:y_data}))

#cost 를 실행시키면 cost 의 값이 반환되기 때문에 바로 run 해주면 됨

    a=sess.run(hypothesis, feed_dict={x:x_data[0:3]})
    print(a)
    print(a.sum(axis=1))

0 12.517687
500 0.8895432
1000 0.7030611
1500 0.62408996
2000 0.57749796
[[0.09416647 0.20733286 0.69850063]
 [0.049133   0.26790535 0.6829617 ]
 [0.01029027 0.53761554 0.4520941 ]]
[1.        1.        0.9999999]


In [69]:
x_data = [[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

x = tf.placeholder("float",[None, 4])
y = tf.placeholder("float",[None, 3])
# tf.float32 대신 "float" 도 가능
nb_classes = 3

w = tf.Variable(tf.random_normal([4,nb_classes]), name="weight")
b = tf.Variable(tf.random_normal([1]),name = "bias")

# tf.nn.softmax computes softmax activations
# sotfmax = exp(Logits)/reduce_sum(exp(Logits),dim)
hypothesis = tf.nn.softmax(tf.matmul(x,w)+b)

#Cross entropy cost/Loss
cost = tf.reduce_mean(-tf.reduce_sum(y*tf.log(hypothesis), axis=1))
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

#Launch graph
sess=tf.Session()
sess.run(tf.global_variables_initializer())
    
for i in range(2001):
    sess.run(train, feed_dict = {x:x_data, y:y_data})
        
    if i%500==0:
        print(i, sess.run(cost, feed_dict = {x:x_data,y:y_data}))

#cost 를 실행시키면 cost 의 값이 반환되기 때문에 바로 run 해주면 됨



0 7.498189
500 0.79876775
1000 0.66061735
1500 0.602481
2000 0.56590754


In [72]:
# Testing & One-hot encoding
a=sess.run(hypothesis, feed_dict={x:x_data[0:3]})
print(a, sess.run(tf.arg_max(a,1))) # tf.arg_max() 몇 번째 index의 값이 가장 큰지
#index 를 반환 해줌 # 1은 축을 의미 # sum 에서의 aixs=1 인 것과 비슷한 것으로 생각하면 됨
# 하나의 데이터에 대해서 해도 hypothesis 는 [[]] 의 형식으로 나오기 때문에 축은 1을 기준으로!
print(a.sum(axis=1))

[[0.07927699 0.14761211 0.77311087]
 [0.03931756 0.24921188 0.71147054]
 [0.01632147 0.5229236  0.46075496]] [2 2 1]
[1. 1. 1.]


## Fancy softmax Classification

### softmax_cross_entropy_with_logits

In [ ]:
logits = tf.matmul(x,w) + b
hypothesis = tf.nn.softmax(logits)

# Cross entropy cost/Loss
cost = tf.reduce_mean(-tf.reduce_sum(y*tf.log(hypothesis), axis=1))
# 원래는 이런 과정으로 cost 의 수식을 직접 기입

# Cross entropy cost/Loss
cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y_one_hot)
cost = tf.reduce_mean(cost_i)

## train1

In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
import tensorflow as tf

## 데이터 정제

In [109]:
data = pd.read_csv("./iris.csv")

In [89]:
data["Species"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [111]:
for idx, i in enumerate(data["Species"].unique()):
    data.loc[data["Species"]==i,"Species"]=idx

In [112]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
Id               150 non-null int64
SepalLengthCm    150 non-null float64
SepalWidthCm     150 non-null float64
PetalLengthCm    150 non-null float64
PetalWidthCm     150 non-null float64
Species          150 non-null int64
dtypes: float64(4), int64(2)
memory usage: 7.1 KB


In [102]:
data.loc[data["Species"]==0,"y_1"]=1
data.loc[data["Species"]==1,"y_2"]=1
data.loc[data["Species"]==2,"y_3"]=1

In [113]:
data=data.drop(["Id"], axis=1)

In [115]:
data.to_csv("data-iris.csv", header=False,index=False)

In [ ]:
data.fillna(0)

In [116]:
data

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0              5.1           3.5            1.4           0.2        0
1              4.9           3.0            1.4           0.2        0
2              4.7           3.2            1.3           0.2        0
3              4.6           3.1            1.5           0.2        0
4              5.0           3.6            1.4           0.2        0
5              5.4           3.9            1.7           0.4        0
6              4.6           3.4            1.4           0.3        0
7              5.0           3.4            1.5           0.2        0
8              4.4           2.9            1.4           0.2        0
9              4.9           3.1            1.5           0.1        0
10             5.4           3.7            1.5           0.2        0
11             4.8           3.4            1.6           0.2        0
12             4.8           3.0            1.4           0.1        0
13             4.3           3.0            1.1           0.1        0
14             5.8           4.0            1.2           0.2        0
15             5.7           4.4            1.5           0.4        0
16             5.4           3.9            1.3           0.4        0
17             5.1           3.5            1.4           0.3        0
18             5.7           3.8            1.7           0.3        0
19             5.1           3.8            1.5           0.3        0
20             5.4           3.4            1.7           0.2        0
21             5.1           3.7            1.5           0.4        0
22             4.6           3.6            1.0           0.2        0
23             5.1           3.3            1.7           0.5        0
24             4.8           3.4            1.9           0.2        0
25             5.0           3.0            1.6           0.2        0
26             5.0           3.4            1.6           0.4        0
27             5.2           3.5            1.5           0.2        0
28             5.2           3.4            1.4           0.2        0
29             4.7           3.2            1.6           0.2        0
..             ...           ...            ...           ...      ...
120            6.9           3.2            5.7           2.3        2
121            5.6           2.8            4.9           2.0        2
122            7.7           2.8            6.7           2.0        2
123            6.3           2.7            4.9           1.8        2
124            6.7           3.3            5.7           2.1        2
125            7.2           3.2            6.0           1.8        2
126            6.2           2.8            4.8           1.8        2
127            6.1           3.0            4.9           1.8        2
128            6.4           2.8            5.6           2.1        2
129            7.2           3.0            5.8           1.6        2
130            7.4           2.8            6.1           1.9        2
131            7.9           3.8            6.4           2.0        2
132            6.4           2.8            5.6           2.2        2
133            6.3           2.8            5.1           1.5        2
134            6.1           2.6            5.6           1.4        2
135            7.7           3.0            6.1           2.3        2
136            6.3           3.4            5.6           2.4        2
137            6.4           3.1            5.5           1.8        2
138            6.0           3.0            4.8           1.8        2
139            6.9           3.1            5.4           2.1        2
140            6.7           3.1            5.6           2.4        2
141            6.9           3.1            5.1           2.3        2
142            5.8           2.7            5.1           1.9        2
143            6.8           3.2            5.9           2.3        2
144            6.7           

## model - iris

In [20]:
from sklearn.preprocessing import MinMaxScaler
xy = pd.read_csv("./data-iris.csv",dtype=np.float32)
xy = np.array(xy, dtype=np.float32)

x_train = xy[:,0:-1]
y_train = xy[:,[-1]]
x_train = MinMaxScaler().fit_transform(x_train)

nb_classes = 3

x = tf.placeholder("float", [None, 4])

y = tf.placeholder(tf.int32, [None, 1]) # y_one_hot 의 사용을 위해 int 형식으로 받음!

w = tf.Variable(tf.random_normal([4, nb_classes]), name = "weight")
b = tf.Variable(tf.random_normal([nb_classes]), name = "bias")


logits = tf.matmul(x,w) + b
hypothesis = tf.nn.softmax(logits)

y_one_hot = tf.one_hot(y,nb_classes ) # dtype 이 int 인 것만 받을 수 있음!!!
y_one_hot = tf.reshape(y_one_hot , [-1, nb_classes]) #reshape 에서 None 은 -1 의 형식으로 들어감!

cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels = y_one_hot)
# 한개의 인스턴스에 대한 cost의 합이 나옴
cost = tf.reduce_mean(cost_i)

train = tf.train.GradientDescentOptimizer(learning_rate = 0.01).minimize(cost)

prediction = tf.argmax(hypothesis, 1) # axis =1 에 대한 agrmax 값
correct_prediction = tf.equal(prediction, tf.argmax(y_one_hot,1)) # tf.arg_max 와 동일
accuracy = tf.reduce_mean(tf.cast(correct_prediction, 1))

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(1301):
    a,b,_ = sess.run([accuracy, cost, train], feed_dict = {x:x_train, y:y_train})
    if step%400 == 0 :
        print("Step: {:5}\tLoss: {:.3f}\tAcc:{:.2%}".format(step, b, a))
        # 앞에껀 상관 없고, 실수형 소숫점 셋째자리 까지, # 앞에껀 상관없고, %형 소숫점 2째자리 까지
        # :5 칸을 일정하게 유지시켜주는 역할. 

pred = sess.run(prediction, feed_dict={x:x_train})

for a,b in zip(pred, y_train.flatten()): # pred 가 1열만 가지게 되면서 하나의 리스트에 들어간 형태(1차원)가
    #되기 때문에 y_train 또한 flatten 으로 1차원으로 펴주게됨
    print("[{}] Prediction : {} True Y: {}".format(a==int(b), a, int(b)))
    # y_train 의 경우에 float 의 형태이기 때문에 int 로 바꾸어주게 됨!

Step:     0	Loss: 0.800	Acc:65.77%
Step:   400	Loss: 0.660	Acc:87.25%
Step:   800	Loss: 0.603	Acc:89.26%
Step:  1200	Loss: 0.562	Acc:92.62%
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y

In [11]:
print(xy)

[[0.16666663 0.4166667  0.0677966  0.04166667 0.        ]
 [0.11111104 0.50000006 0.05084746 0.04166667 0.        ]
 [0.08333325 0.4583333  0.08474576 0.04166667 0.        ]
 [0.19444442 0.66666657 0.0677966  0.04166667 0.        ]
 [0.30555558 0.7916667  0.11864409 0.125      0.        ]
 [0.08333325 0.5833333  0.0677966  0.08333333 0.        ]
 [0.19444442 0.5833333  0.08474576 0.04166667 0.        ]
 [0.02777779 0.37500006 0.0677966  0.04166667 0.        ]
 [0.16666663 0.4583333  0.08474576 0.         0.        ]
 [0.30555558 0.7083333  0.08474576 0.04166667 0.        ]
 [0.13888896 0.5833333  0.10169491 0.04166667 0.        ]
 [0.13888896 0.4166667  0.0677966  0.         0.        ]
 [0.         0.4166667  0.01694916 0.         0.        ]
 [0.41666675 0.8333333  0.03389831 0.04166667 0.        ]
 [0.38888884 1.         0.08474576 0.125      0.        ]
 [0.30555558 0.7916667  0.05084746 0.125      0.        ]
 [0.22222221 0.62499994 0.0677966  0.08333333 0.        ]
 [0.38888884 0

In [150]:
print(sess.run(y_one_hot, feed_dict={y:y_train}))
print(y_train)


[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [21]:
from sklearn.preprocessing import MinMaxScaler
filename_queue = tf.train.string_input_producer(["./data-iris.csv"],shuffle=False, name="filename_queue")

reader=tf.TextLineReader()
key,value = reader.read(filename_queue)

record_defaults = [[0.],[0.],[0.],[0.],[0]]
xy = tf.decode_csv(value, record_defaults = record_defaults)

min_after_dequeue = 10
capacity = min_after_dequeue + 3 * 50
train_x_batch, train_y_batch = tf.train.shuffle_batch([xy[0:-1],xy[-1:]], batch_size = 30,
                                                     capacity = capacity, min_after_dequeue = min_after_dequeue)

nb_classes = 3

x = tf.placeholder("float", [None, 4])
y = tf.placeholder(tf.int32, [None, 1])

w = tf.Variable(tf.random_normal([4, nb_classes]), name = "weight")
b = tf.Variable(tf.random_normal([nb_classes]), name = "bias")


logits = tf.matmul(x,w) + b
hypothesis = tf.nn.softmax(logits)

y_one_hot = tf.one_hot(y,nb_classes )
y_one_hot = tf.reshape(y_one_hot , [-1, nb_classes]) #reshape 에서 None 은 -1 의 형식으로 들어감!

cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels = y_one_hot)
# 한개의 인스턴스에 대한 cost의 합이 나옴
# -tf.reduce_sum(tf.log(hypothesis)*y_one_hot) 와 동일함
cost = tf.reduce_mean(cost_i)

train = tf.train.GradientDescentOptimizer(learning_rate = 1e-4).minimize(cost)

prediction = tf.argmax(hypothesis, 1)
correct_prediction = tf.equal(prediction, tf.argmax(y_one_hot,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, 1))

sess = tf.Session()
sess.run(tf.global_variables_initializer())

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_train, y_train = sess.run([train_x_batch, train_y_batch])
    x_train = MinMaxScaler().fit_transform(x_train)
    c_val,_ = sess.run([cost, train], feed_dict = {x:x_train, y:y_train})
    if step%200 == 0:
        print(c_val)

INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Expect 5 fields but have 21 in record 0
	 [[{{node DecodeCSV_2}}]]


OutOfRangeError: RandomShuffleQueue '_62_shuffle_batch_1/random_shuffle_queue' is closed and has insufficient elements (requested 30, current size 1)
	 [[node shuffle_batch_1 (defined at C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]

Original stack trace for 'shuffle_batch_1':
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 422, in run_forever
    self._run_once()
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 1432, in _run_once
    handle._run()
  File "C:\ProgramData\Anaconda3\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-21-db1d592a4396>", line 13, in <module>
    capacity = capacity, min_after_dequeue = min_after_dequeue)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\training\input.py", line 1347, in shuffle_batch
    name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\training\input.py", line 874, in _shuffle_batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\ops\data_flow_ops.py", line 489, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\ops\gen_data_flow_ops.py", line 3862, in queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()


## train2 - mobile

In [23]:
data = pd.read_csv("./mobile-train.csv", dtype = np.float32)
data.head(5)

battery_power  blue  clock_speed  dual_sim    fc  four_g  int_memory  \
0          842.0   0.0          2.2       0.0   1.0     0.0         7.0   
1         1021.0   1.0          0.5       1.0   0.0     1.0        53.0   
2          563.0   1.0          0.5       1.0   2.0     1.0        41.0   
3          615.0   1.0          2.5       0.0   0.0     0.0        10.0   
4         1821.0   1.0          1.2       0.0  13.0     1.0        44.0   

   m_dep  mobile_wt  n_cores     ...       px_height  px_width     ram  sc_h  \
0    0.6      188.0      2.0     ...            20.0     756.0  2549.0   9.0   
1    0.7      136.0      3.0     ...           905.0    1988.0  2631.0  17.0   
2    0.9      145.0      5.0     ...          1263.0    1716.0  2603.0  11.0   
3    0.8      131.0      6.0     ...          1216.0    1786.0  2769.0  16.0   
4    0.6      141.0      2.0     ...          1208.0    1212.0  1411.0   8.0   

   sc_w  talk_time  three_g  touch_screen  wifi  price_range  
0   7.0       19.0      0.0           0.0   1.0          1.0  
1   3.0        7.0      1.0           1.0   0.0          2.0  
2   2.0        9.0      1.0           1.0   0.0          2.0  
3   8.0       11.0      1.0           0.0   0.0          2.0  
4   2.0       15.0      1.0           1.0   0.0          1.0  

[5 rows x 21 columns]

In [170]:
len(data["price_range"].unique())

4

In [24]:
nb_classes = len(data["price_range"].unique())
xy = np.array(data, dtype = np.float32)

x_train = xy[:,:-1]
y_train = xy[:,[-1]]

x = tf.placeholder("float",[None,20])
y = tf.placeholder(tf.int32, [None,1])

y_one_hot = tf.one_hot(y, nb_classes)
y_one_hot = tf.reshape(y_one_hot, [-1,nb_classes])

w = tf.Variable(tf.random_normal([20,nb_classes]), name="weight")
b = tf.Variable(tf.random_normal([nb_classes]), name = "bias")

logits = tf.matmul(x,w) + b
hypothesis = tf.nn.softmax(logits)

cost_i = tf.nn.softmax_cross_entropy_with_logits(logits = logits, labels = y_one_hot)
cost = tf.reduce_mean(cost_i)

train = tf.train.GradientDescentOptimizer(learning_rate = 1e-4).minimize(cost)

prediction = tf.argmax(hypothesis, 1)
correct_prediction = tf.equal(prediction, tf.argmax(y_one_hot, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, 1))

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for i in range(10001):
    sess.run(train, feed_dict = {x:x_train, y:y_train})
    if i%500==0:
        print("step", i)
        print("accuacy:", sess.run(accuracy, feed_dict = {x:x_train,y:y_train}))
        print("cost", sess.run(cost, feed_dict = {x:x_train, y:y_train}))

step 0
accuacy: 0.25
cost 4682.079
step 500
accuacy: 0.414
cost 160.32437
step 1000
accuacy: 0.429
cost 193.24208
step 1500
accuacy: 0.466
cost 144.64323
step 2000
accuacy: 0.4585
cost 178.63159
step 2500
accuacy: 0.473
cost 48.520454
step 3000
accuacy: 0.3705
cost 108.7127
step 3500
accuacy: 0.517
cost 67.619705
step 4000
accuacy: 0.3835
cost 70.26634
step 4500
accuacy: 0.527
cost 124.032394
step 5000
accuacy: 0.4955
cost 167.81972
step 5500
accuacy: 0.5135
cost 83.7751
step 6000
accuacy: 0.437
cost 81.76464
step 6500
accuacy: 0.5715
cost 105.31384
step 7000
accuacy: 0.566
cost 144.92616
step 7500
accuacy: 0.6395
cost 17.224457
step 8000
accuacy: 0.4215
cost 86.742455
step 8500
accuacy: 0.4605
cost 59.428986
step 9000
accuacy: 0.4435
cost 54.70692
step 9500
accuacy: 0.501
cost 81.07881
step 10000
accuacy: 0.517
cost 49.714485


In [25]:
test = pd.read_csv("./mobile-test.csv", dtype = np.float32)
test
result = sess.run(hypothesis, feed_dict = {x:test})

ValueError: Cannot feed value of shape (1000, 21) for Tensor 'Placeholder_34:0', which has shape '(?, 20)'

In [26]:
filename_queue = tf.train.string_input_producer(["./mobile-train.csv"],shuffle=False, name="filename_queue")

reader=tf.TextLineReader()
key,value = reader.read(filename_queue)

record_defaults = [[0.],[0.],[0.],[0.],[0.]]
xy = tf.decode_csv(value, record_defaults = record_defaults)

min_after_dequeue = 10
capacity = min_after_dequeue + 3 * 50
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1],xy[-1:]], batch_size = 30)

nb_classes = 4

x = tf.placeholder("float", [None, 20])
y = tf.placeholder(tf.int32, [None, 1])

w = tf.Variable(tf.random_normal([20, nb_classes]), name = "weight")
b = tf.Variable(tf.random_normal([nb_classes]), name = "bias")

logits = tf.matmul(x,w) + b
hypothesis = tf.nn.softmax(logits)

y_one_hot = tf.one_hot(y,nb_classes )
y_one_hot = tf.reshape(y_one_hot , [-1, nb_classes]) #reshape 에서 None 은 -1 의 형식으로 들어감!

cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels = y_one_hot)
# 한개의 인스턴스에 대한 cost의 합이 나옴
# -tf.reduce_sum(tf.log(hypothesis)*y_one_hot) 와 동일함
cost = tf.reduce_mean(cost_i)

train = tf.train.GradientDescentOptimizer(learning_rate = 0.01).minimize(cost)

prediction = tf.argmax(hypothesis, 1)
correct_prediction = tf.equal(prediction, tf.argmax(y_one_hot,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, 1))

sess = tf.Session()
sess.run(tf.global_variables_initializer())

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_train, y_train = sess.run([train_x_batch, train_y_batch])
    x_train = MinMaxScaler().fit_transform(x_train)
    c_val = sess.run([cost, train], feed_dict = {x:x_train, y:y_train})
    print(c_val)
    print("accuracy : ", sess.run([accuracy], feed_dict = {x:x_train, y:y_train}))

INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Expect 5 fields but have 21 in record 0
	 [[{{node DecodeCSV_2}}]]


OutOfRangeError: FIFOQueue '_75_batch_4/fifo_queue' is closed and has insufficient elements (requested 30, current size 0)
	 [[node batch_4 (defined at C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]

Original stack trace for 'batch_4':
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 422, in run_forever
    self._run_once()
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 1432, in _run_once
    handle._run()
  File "C:\ProgramData\Anaconda3\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-26-5f96a22d3f77>", line 11, in <module>
    train_x_batch, train_y_batch = tf.train.batch([xy[0:-1],xy[-1:]], batch_size = 30)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\training\input.py", line 1020, in batch
    name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\training\input.py", line 789, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\ops\data_flow_ops.py", line 489, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\ops\gen_data_flow_ops.py", line 3862, in queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
