## Shape, axis

In [14]:
import numpy as np
import tensorflow as tf

In [12]:
t = np.arange(0,5, dtype=np.float32)
t.ndim

1

In [35]:
aa=np.arange(10).reshape(-1,5)
aa.ndim

2

In [39]:
t=tf.constant([1,2,3,4])
t2=tf.shape(t)
sess =tf.Session()
t2.eval(session=sess)
# numpy 의 shape 와 tf 의 shape는 같은 역할을 함. [rank,rank,rank,rank,rank]
# [rank,rank] => 몇행 몇열

# 맨 밖에서 부터 [0,1,2,3,4] 4의 축을 -1이라고 부르기도 함 [0,1,2,3,-1]
#axis = 0, axis=1

array([4])

In [46]:
matrix1 = tf.constant([[1,2],[4,5]], dtype = tf.float32)
matrix2 = tf.constant([[1],[2]], dtype = tf.float32)
print(matrix1.shape) # 굳이 session 의 실행 없이도 알아볼 수 있음!!!
print(matrix2.shape)
matrix = tf.matmul(matrix1, matrix2)
print(matrix.shape)

# shape 는 굳이 session 의 실행 없이도 알아볼 수 있음

(2, 2)
(2, 1)
(2, 1)


## Broad casting

shape 이 다르더라도 곱이 가능하게 해줌

In [54]:
matrix1 = tf.constant([[1,2]])
matrix2 = tf.constant(3)
# 브로드 캐스팅 결과가 [[]] 로 나옴

matrix1 = tf.constant([[1,2]])
matrix2 = tf.constant([3,4])
# 브로드 캐스팅 결과가 1을 따라서 [[]] 로 나옴

matrix1 = tf.constant([[1,2]])
matrix2 = tf.constant([[1],[2]])
print((matrix1*matrix2).eval(session=tf.Session()))
# 브로드 캐스팅 결과가 1와 2를 따라서 [[],[]] 로 나옴

array([[1, 2],
       [2, 4]])

## reduce mean/sum

In [53]:
tf.reduce_mean([1,2], axis=0).eval(session=tf.Session())
# 데이터 type 이 integer 이면 결과값도 integer로 나오게 됨!
#조심조심조심조심조심!!!

1

In [58]:
x = [[1.,2.],[3.,4.]]
print(tf.reduce_mean(x, axis=1).eval(session=tf.Session()))
print(tf.reduce_mean(x, axis=0).eval(session=tf.Session()))
print(tf.reduce_mean(x, axis=-1).eval(session=tf.Session()))

[1.5 3.5]
[2. 3.]
[1.5 3.5]


In [65]:
x= [[0,1,2],[3,4,5]]
print(tf.argmax(x).eval(session=tf.Session())) # argmax의 디폴트 값은 0, 대부분의 디폴트 값은 0
print(tf.argmax(x,1).eval(session=tf.Session()))
print(tf.argmax(x,-1).eval(session=tf.Session()))

[1 1 1]
[2 2]
[2 2]


## data 형태 변환

In [71]:
t = np.arange(12).reshape(-1,3)
print(t)
print(tf.reshape(t, shape=(-1,3)).eval(session=tf.Session()))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [87]:
print(tf.squeeze(t).eval(session=tf.Session()))
print(tf.squeeze([[[0],[1],[2]]]).eval(session=tf.Session()))
# squeeze 라는 것은 [[[0],[1],[2]]] 이런 형식의 데이터 [3,1,1] / [3,1] 일 때 [3] 으로 펴주게 됨
# 다른 형태이면 아무것도 안함
# numpy 의 flatten 은 어떤 형식이던지 쫙 펴줌 => 행을 기준으로 펴주게 됨

print(tf.expand_dims([[0,1,2]],2).eval(session=tf.Session())) # [data, 늘릴 차원] 
# ex) [data, 1] => 1차원을 늘리겠다 ex) [data,2] => 2차원을 늘리겠다

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[[0]
  [1]
  [2]]]


## One hot

In [89]:
tf.one_hot([[0],[1],[2],[0]], depth = 3).eval(session=tf.Session())
# depth 는 y의 unique() 의 개수
# 차원이 하나 늘어나게 됨
# [[0,1,0,0]] 으로 나오기 때문에!

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

## cast

In [91]:
print(tf.cast([1.8,2.2,3.3], dtype=tf.int32).eval(session=tf.Session()))
print(tf.cast([True,False,1==1,1!=1], dtype=tf.int32).eval(session=tf.Session()))

[1 2 3]
[1 0 1 0]


## stack

In [96]:
x=[[1,3]]
y=[[2,5]]
z=[[3,6]]
print(tf.stack([x,y,z]).eval(session=tf.Session())) # 디폴트는 0임
print(tf.stack([x,y,z],1).eval(session=tf.Session()))
print(tf.stack([x,y,z],2).eval(session=tf.Session()))
 
# 어떤 방향으로 쌓던지 한차원이 늘어나게 됨
# stack 에서의 axis는 쌓은 뒤 한차원이 늘어났을 때의 axis 임

[[[1 3]]

 [[2 5]]

 [[3 6]]]
[[[1 3]
  [2 5]
  [3 6]]]
[[[1 2 3]
  [3 5 6]]]


## Ones and Zeros like  
똑같은 형태, dtype의 0으로 가득찬/1로 가득찬 array 를 생성하고 싶을 때 사용

In [99]:
x = [[0.,1.,2.],[2.,1.,0.]]
 
print(tf.ones_like(x).eval(session=tf.Session()))
print(tf.zeros_like(x).eval(session=tf.Session()))

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


## Zip

In [100]:
for a,b in zip([1,2,3],[4,5,6]):
    print(a,b)

1 4
2 5
3 6


In [ ]:
import seaborn as sns
import numpy as np
titanic = sns.load_dataset('titanic')
df = titanic[['age','fare','pclass']][:10]
df # titanic 데이터 불러오기 